
# Placeholders:
# {player}
# {symbol}
# {balance}
# {currency_name}
# {time_left}
# {earned}

sql:
  host: "localhost"
  port: 5432
  database: "database"
  username: "postgres"
  password: "password"
  pool_size: 3

use_permissions: false
initial_balance: 100.0

currency:
  symbol: $
  name: Dollars
  format: "###,###,###,###,###,###,###,###.00"
  collapse: true